ppo_cartpole_pixel:
  algo: ppo
  env_id: CartPole-v1
  obs: pixel
  num_envs: 8
  rollout_steps: 128
  update_epochs: 4
  batch_size: 256
  gamma: 0.99
  gae_lambda: 0.95
  clip_coef: 0.2
  vf_coef: 0.5
  ent_coef: 0.01
  learning_rate: 2.5e-4
  max_grad_norm: 0.5

ppo_walker2d_pixel:
  algo: ppo
  env_id: Walker2d-v5
  obs: pixel
  num_envs: 4
  rollout_steps: 256
  update_epochs: 10
  batch_size: 256
  gamma: 0.99
  gae_lambda: 0.95
  clip_coef: 0.2
  vf_coef: 0.5
  ent_coef: 0.0
  learning_rate: 3e-4
  max_grad_norm: 0.5
