algo: sac
alpha: 0.2
alpha_lr: 1e-4
auto_alpha: true
batch_size: 256
buffer_size: 200000
env_id: Hopper-v5
env_kwargs:
  ctrl_cost_weight: 0.05
  forward_reward_weight: 0.7
  healthy_reward: 0.6
  max_episode_steps: 20000
gamma: 0.99
learning_rate: 3e-4
learning_starts: 5000
max_grad_norm: 10.0
obs: pixel
target_entropy_coef: 0.45
tau: 0.005
train_freq: 1
